### PR TITLE
new specific image registration techniques

### PR DESCRIPTION
**Pull request by lzehl**
related to #195

### CODE REVIEW

**Comment by lzehl** [comment]
@skoehnen maybe you can add a nice one sentence definition? I wasn't sure what to say (e.g., I assume they are both non-linear image registration techniques?)

**Comment by skoehnen** [comment]
@lzehl Are these definitions okay?

**Comment by lzehl** [comment]
@skoehnen I've updated the instances a bit. Could you double check?

**Review by skoehnen — APPROVED** [review]
Looks good to me.

**Pull request merged**
