### PR TITLE
Add LearningResourceType and EducationalLevel

### PR DESCRIPTION
**Pull request by apdavison**
cf https://github.com/HumanBrainProject/openMINDS_publications/pull/2 and https://github.com/HumanBrainProject/openMINDS_core/issues/211

### CODE REVIEW

**Comment by lzehl** [comment]
@apdavison is this still in progress or should one of us have a look at this already?
Maybe I can wait for the controlledTerms/EducationalLevel (cf. my comment in your other PR)

**Comment by apdavison** [comment]
You can look at this already. More terms could be added, my aim was to add those that could be most immediately useful.

**Review by lzehl — COMMENTED** [review]
@apdavison to finalize the integration of the new extensions we need to merge your PR as fast as possible. 

Overall the PR looks good. I corrected some indent issues and smaller things. I also added the two missing terminology instances. Please double check those and give me your okay for merging.

**Comment by apdavison** [comment]
ok to merge

**Pull request merged**
