### PR TITLE
Create isometricMapping.jsonld

### PR DESCRIPTION
**Pull request by lzehl**

### CODE REVIEW

**Comment by lzehl** [comment]
@mdenker could you double check the definition of this technique? thanks in advance

**Comment by mdenker** [comment]
Though I'm no expert here, in my understanding, this entry is still unprecise. I would define isometric mapping, in general, as the process of mapping a source space onto a target space, such that the distance between any source points is equal to that between mapped target points. In the special case of low-dimensional embedding of a measurement space using a non-linear technique, isometric mapping would refer to techniques that likewise preserve -- to some degree -- the distances in the low-dimensional space. In this respect I find that ISOMAP (the wikipedia article) would represent one particular type of such isometric mappings. For example, Multi-dimensional Scaling would be another such technique that approximately preserves distances. Thus, depending on what should be modelled here, I would either rename the method to ISOMAP if that specific technique is meant, or broaden the definition to be less specific about the algorithm.

**Comment by lzehl** [comment]
@mdenker thank you a lot for the feedback. Indeed the ISOMAP is for now the issue. I will also add isometric mapping as the super class. I'll pin you again to double check the definitions.

**Comment by UlrikeS91** [comment]
Replaced by PR https://github.com/openMetadataInitiative/openMINDS_instances/pull/83

**Pull request closed without merging**
