### PR TITLE
Add units core-hour and wafer-hour

### PR DESCRIPTION
**Pull request by apdavison**
Needed for resource usage provenance metadata (openMINDS/computation)

### CODE REVIEW

**Comment by lzehl** [comment]
@apdavison do you need a review for this PR?

**Comment by apdavison** [comment]
@lzehl yes please

**Review by lzehl — COMMENTED** [review]
@apdavison thank you for this PR (:) quite important for computation, sorry we forgot about those...)

I have only one question: are there no abbreviations/symbols for core-hour and wafer-hour you could add as synoyms (cf. PR #61)?

**Comment by apdavison** [comment]
since these are not very commonly used or familiar units, I think it's safest not to abbreviate them. "core-h" would be possible, but I think it would confuse most people.

**Comment by lzehl** [comment]
@apdavison okay. then let's merge them, but we need to find a solution for #61 as well. could you have a look at that one as well?

**Pull request merged**
