### PR TITLE
Cleanup of categories and adding of AnalysisTechnique

### PR DESCRIPTION
**Pull request by lzehl**
+ adding category "anatomicalLocation" to: CellType, Organ, OrganismSubstance, SubcellularEntity, UBERONParcellation
+ adding category "technique" to: AnalysisTechnique, StimulationTechnique, Technique
+ adding new schema AnalysisTechnique
+ adding new instance for Terminology ("analysis technique")
+ adding one instance for AnalysisTechnique

### CODE REVIEW

**Comment by lzehl** [comment]
@UlrikeS91 I hope I've got everything.

**Comment by UlrikeS91** [comment]
> @UlrikeS91 I hope I've got everything.

Yes and no, you had everything before I noticed that my list was missing something 😆 

Would you mind adding the new terminology `LivePaperSectionType` to this PR? Details are described in https://github.com/HumanBrainProject/openMINDS_publications/pull/12 and I added it to my sheet as well (if you want to add the PR reference as you did for all the other ones).

**Comment by lzehl** [comment]
@apdavison I need your input / feedback for the new controlled terms for LivePaperSectionType:
+ xxxSection or xxxPaperSection or xxxLivePaperSection ??
+ customXXX definition: "A 'custom XXX' is used to describe custom elements within a live paper." ??
+ genericXXX definition: "A 'generic XXX' is used to describe generic elements within a live paper." ??
+ modelXXX (or computationalModelXXX ?) definition: "A 'model XXX' is used to describe a model element within a live paper." ??
+ morphologyXXX (or neuronMorphologyXXX ?) definition: "A 'morphology XXX' is used to describe a morphology element within a live paper." ??
+ traceXXX (or neuronalTraceXXX ?) definition: "A 'trace XXX' is used to describe a trace element within a live paper." ??

**Comment by apdavison** [comment]
Hi @lzehl - please remove the controlled terms for LP section types.

**Comment by lzehl** [comment]
@apdavison & @UlrikeS91 LivePaperSectionTypes are removed from this PR (based on decision in cf. https://github.com/HumanBrainProject/openMINDS_publications/pull/12#issuecomment-1446214026)

**Comment by lzehl** [comment]
@aeidi89 feel free to merge if you approve this PR now
(@apdavison concerns were addressed)

**Review by aeidi89 — COMMENTED** [review]
Looks good. 
It would be good to have the definition for analysis technique, it is a bit vague for me.

@lzehl 
Is this what is meant by analysis technique?

'Analysis technique' is a method used to determine a chemical or physical property of a chemical substance, chemical element, or mixture. There is a wide variety of techniques used for analysis, from simple weighing to advanced techniques using highly specialized instrumentation, (from [Wikipedia](https://en.wikipedia.org/wiki/Analytical_technique#:~:text=Analytical%20technique%20is%20a%20method,techniques%20using%20highly%20specialized%20instrumentation)).

**Comment by lzehl** [comment]
@aeidi89 no that definition does not make sense. It is way too specific. An 'analysis technique' refers to any mathematical analysis applied to any type of data.

I will add definitions for all terminologies later on (none of them have one at the moment). I think we should do this in a separate PR.

**Review by aeidi89 — APPROVED** [review]
Looks good.

**Comment by aeidi89** [comment]
@lzehl Thank you for explaining, the ward clustering makes more sense then as well. I'll merge and close this PR.

**Pull request merged**
