### PR TITLE
New StimulationApproach/StimulusType instances

### PR DESCRIPTION
**Pull request by UlrikeS91**
related to #64 suggested by @eapapp

This is still a draft, so that we can add some additional stimulusType instances as well. 

So far, I added all stimulus modalities collected on InterLex as stimulationApproaches: https://neuinfo.org/interlex/view/ilx_0111059#children. This was anyway the plan. One of those is, of course, "visual stimulation" 😉

### CODE REVIEW

**Review by lzehl — APPROVED** [review]

**Comment by lzehl** [comment]
@UlrikeS91 thanks :+1: is this ready to go then? you still have it as a draft

**Comment by lzehl** [comment]
@UlrikeS91 I'm a bit confused...  and double checked now... We do not distinguish between stimulationApproach and stimulationType in any v4 schema (they were introduced for ephys which is not part of v4)... We only have Stimulation in BehavioralProtocol and Protocol. If we want to have them in we need to change the schemas as well.

**Comment by UlrikeS91** [comment]
> @UlrikeS91 I'm a bit confused... and double checked now... We do not distinguish between stimulationApproach and stimulationType in any v4 schema (they were introduced for ephys which is not part of v4)... We only have Stimulation in BehavioralProtocol and Protocol. If we want to have them in we need to change the schemas as well.

Some confusion as stated in the related issue, so ignore this comment. This PR remains a draft until I've added the stimulusTypes needed for dataset that was described in the issue.

**Comment by lzehl** [comment]
Thanks for keeping an eye on things if I'm getting confused :sweat_smile:

**Review by lzehl — APPROVED** [review]

**Pull request merged**
