### PR TITLE
Create interpolation.jsonld

### PR DESCRIPTION
**Pull request by lzehl**

### CODE REVIEW

**Review by skoehnen — APPROVED** [review]
The definition looks good to me.
But we should be careful when we use this technique, since it is quite broad.

**Comment by skoehnen** [comment]
@lzehl Should we start to add some more specific interpolation methods?
From the top of my head I could add:

- linear, cosine, cubic, hermite and their (3D equivalents if we want to be that specific)
- Bi- and Tri-linear
- Different fitting functions
- Nearest neighbor

And I bet there are a lot more ;)

I keep this PR open for now, but maybe we should move this to a issue.

**Comment by lzehl** [comment]
@skoehnen very good idea, but let's move this to another PR. you don't have to create and issue. would you take this PR over?

**Comment by skoehnen** [comment]
> @skoehnen very good idea, but let's move this to another PR. you don't have to create and issue. would you take this PR over?

Yes, I will open a new PR with some more specific methods.

**Pull request merged**
